name: Push to Github2Wordpress Repository
on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - 'src/site/notes/**.md'

jobs:
  push-to-b-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a repo
        uses: actions/checkout@v3
        with:
          repository: dangehub/qlog
          path: qlog
          ref: main
          token: ${{ secrets.ACCESS_TOKEN2 }}
  
          
      - name: Checkout b repo
        uses: actions/checkout@v3
        with:
          repository: dangehub/github2wp
          path: github2wp
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Copy files from a to b local
        run: |
          cp -r qlog/src/site/notes/* github2wp/_posts/     


      - name: Find and copy pictures from a to b
        run: |
          # 找到所有 `qlog/src/site/img/user` 下的文件夹
          for dir in $(find qlog/src/site/img/user/* -type d); do
            # 获取文件夹名称作为变量部分
            var_name=$(basename "$dir")
            
            # 确保目标路径存在
            mkdir -p "github2wp/_posts/$var_name/"
            
            # 将文件夹中的所有文件复制到目标路径
            cp -r "$dir/"* "github2wp/_posts/$var_name/"
          done

      - name: Commit and push
        run: |
          cd ./github2wp
          git config --global user.email "moruotaiqing@gmail.com"
          git config --global user.name "dangehub"
          git add -A
          git commit -m "Synced posts" || exit 0
          git push
